// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYe5FRCL8GnIh9izr7GfDXnKECXbcLwPM',
    appId: '1:776184762279:web:f82e348962a1ba49397082',
    messagingSenderId: '776184762279',
    projectId: 'bluecoin-9af7d',
    authDomain: 'bluecoin-9af7d.firebaseapp.com',
    storageBucket: 'bluecoin-9af7d.appspot.com',
    measurementId: 'G-DWMV4B8462',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_5xt2PcgemhxInFEHK92mXItwAhEyWA',
    appId: '1:776184762279:android:7162a17d78840014397082',
    messagingSenderId: '776184762279',
    projectId: 'bluecoin-9af7d',
    storageBucket: 'bluecoin-9af7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvVxNHmU6Pfkz3btfj0ZUhQR1YuClCqY',
    appId: '1:776184762279:ios:4f7536a5e8e79bdb397082',
    messagingSenderId: '776184762279',
    projectId: 'bluecoin-9af7d',
    storageBucket: 'bluecoin-9af7d.appspot.com',
    iosClientId: '776184762279-svd9m3chvc030371h5j4ifuabrv3srvd.apps.googleusercontent.com',
    iosBundleId: 'com.mmm.metricsmeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMvVxNHmU6Pfkz3btfj0ZUhQR1YuClCqY',
    appId: '1:776184762279:ios:f2737e171a1c3f80397082',
    messagingSenderId: '776184762279',
    projectId: 'bluecoin-9af7d',
    storageBucket: 'bluecoin-9af7d.appspot.com',
    iosClientId: '776184762279-ddohtq5n5tl93894dvfnvu4763vdf3lh.apps.googleusercontent.com',
    iosBundleId: 'com.mmm.metricsmeal.RunnerTests',
  );
}
